export const COMMENT_VOTES_ACTION_TYPES = {
    ADD_COMMENT_VOTE_START: 'ADD_COMMENT_VOTE_START',
    ADD_COMMENT_VOTE_SUCCESS: 'ADD_COMMENT_VOTE_SUCCESS',
    ADD_COMMENT_VOTE_ERROR: 'ADD_COMMENT_VOTE_ERROR',
};