
# docker-compose.yml

services:
  mysqlcontainer:
    image: mysql
    container_name: my_mysql_container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: secret
  apachephpcontainer:
    image: nouphet/docker-php4
    container_name: my_php_apache_container
    ports:
      - "8880:80"
      - "8443:443"
    volumes:
      - ./www:/var/www/html
    links:
      - mysqlcontainer