import Head from 'next/head'

export default function Header () {
    return <Head>
    <title>Zabaldu</title>
    <meta name="description" content="Generated by my tanned balls" />
    <meta name="author" content="Zabaldu" />
    <link rel="icon" href="/favicon.ico" />
</Head>;
}

